image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank.jar &



build_script:
  - ./gradlew test -Dselenide.headless=true